sudo: required
services:
    - docker

before_install:
    - docker build -t anujspoddar/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true anujspoddar/docker-react npm run test    
